services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    hostname: namenode
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - /mnt/bigdata/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=cancer_cluster
    env_file:
      - ./hadoop.env

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    hostname: datanode1
    restart: always
    depends_on:
      - namenode
    volumes:
      - /mnt/bigdata/datanode1:/hadoop/dfs/data
    env_file:
      - ./hadoop.env

  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode2
    hostname: datanode2
    restart: always
    depends_on:
      - namenode
    volumes:
      - /mnt/bigdata/datanode2:/hadoop/dfs/data
    env_file:
      - ./hadoop.env

  datanode3:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode3
    hostname: datanode3
    restart: always
    depends_on:
      - namenode
    volumes:
      - /mnt/bigdata/datanode3:/hadoop/dfs/data
    env_file:
      - ./hadoop.env

  api:
    build: .
    container_name: cancer_api
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - datanode3
    environment:
      - HDFS_URL=http://namenode:9870
    volumes:
      - .:/app

  frontend:
    build: ./frontend
    container_name: cancer_frontend
    restart: always
    ports:
      - "5173:5173"
      - "80:5173"
    depends_on:
      - api
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
